LogLevel debug rewrite:trace8

AllowEncodedSlashes NoDecode

<Directory /var/www/html>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

RewriteEngine On
RewriteRule ^(.+\.php)$ $1 [H=application/x-httpd-php]