AllowEncodedSlashes On

ServerRoot "/usr/local/apache2"
Listen 80

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule access_compat_module modules/mod_access_compat.so
LoadModule alias_module modules/mod_alias.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule unixd_module modules/mod_unixd.so

User daemon
Group daemon

ServerName localhost:80

<Directory />
    AllowOverride All
    Require all granted
</Directory>



# 디버깅 로그 설정
ErrorLog /dev/stderr
LogLevel debug rewrite:trace8

DocumentRoot "/usr/local/apache2/htdocs"
<Directory "/usr/local/apache2/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

RewriteEngine On
RewriteRule ^/user/(.*)$ /user/$1/profile.yml [PT]