LogLevel debug authz_core:trace8 authn_file:trace8 proxy:trace8 proxy_fcgi:trace8

AllowEncodedSlashes NoDecode

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    # Apache가 FastCGI로 넘길 때 DocumentRoot(/var/www/html)를 포함한 절대 경로 형태로 SCRIPT_FILENAME 조립
    ProxyFCGIBackendType GENERIC

    <FilesMatch ".+\.ph(?:ar|p|tml)$">
        SetHandler "proxy:unix:/run/php/php8.1-fpm.sock|fcgi://localhost"
    </FilesMatch>


    <Files "admin.php">
        AuthType Basic
        AuthName "Admin Panel"
        AuthUserFile "/etc/apache2/.htpasswd"
        Require valid-user
    </Files>
</VirtualHost>